/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const ScoreEntry = IDL.Record({
  'principal' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'countdownTarget' : IDL.Int,
          'jackpotBalance' : IDL.Nat,
          'totalPlays' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerActor' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCountdownTarget' : IDL.Func([], [IDL.Int], ['query']),
  'getJackpotBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getPayoutWallet' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getTotalPlays' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCountdown' : IDL.Func([IDL.Int], [], []),
  'setPayoutWallet' : IDL.Func([IDL.Principal], [], []),
  'startGame' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'submitScore' : IDL.Func([IDL.Nat], [], []),
  'triggerPayout' : IDL.Func(
      [],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'message' : IDL.Text,
          'amount' : IDL.Nat,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const ScoreEntry = IDL.Record({
    'principal' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'countdownTarget' : IDL.Int,
            'jackpotBalance' : IDL.Nat,
            'totalPlays' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerActor' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCountdownTarget' : IDL.Func([], [IDL.Int], ['query']),
    'getJackpotBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getPayoutWallet' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getTotalPlays' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCountdown' : IDL.Func([IDL.Int], [], []),
    'setPayoutWallet' : IDL.Func([IDL.Principal], [], []),
    'startGame' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'submitScore' : IDL.Func([IDL.Nat], [], []),
    'triggerPayout' : IDL.Func(
        [],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'message' : IDL.Text,
            'amount' : IDL.Nat,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };