/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ScoreEntry {
  'principal' : Principal,
  'score' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'countdownTarget' : bigint,
      'jackpotBalance' : bigint,
      'totalPlays' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCountdownTarget' : ActorMethod<[], bigint>,
  'getJackpotBalance' : ActorMethod<[], bigint>,
  'getLeaderboard' : ActorMethod<[], Array<ScoreEntry>>,
  'getPayoutWallet' : ActorMethod<[], [] | [Principal]>,
  'getTotalPlays' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCountdown' : ActorMethod<[bigint], undefined>,
  'setPayoutWallet' : ActorMethod<[Principal], undefined>,
  'startGame' : ActorMethod<[], { 'ok' : boolean, 'message' : string }>,
  'submitScore' : ActorMethod<[bigint], undefined>,
  'triggerPayout' : ActorMethod<
    [],
    { 'ok' : boolean, 'message' : string, 'amount' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];